[package]
name = "bitset-const"
authors = ["person93 <person93.person93@gmail.com>"]
version = "0.1.0"
edition = "2018"
description = "A statically sized bitset"
license = "MIT"

[dependencies]
bitset-const-macros = { version = "=0.1.0", path = "../macros" }
